services:
  - type: web
    name: hackathon-korkyt-dashboard
    env: python
    rootDir: Hackathon_Korkyt
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0
